name: Fetch Feloopy Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pypinfo

      - name: Fetch stats & build JSON
        run: |
          python - << 'EOF'
          import json, datetime, subprocess, re
          import requests
          from bs4 import BeautifulSoup

          stats = {}

          shield = requests.get('https://img.shields.io/pypi/dt/feloopy.json').json()
          stats['total'] = int(re.sub(r'\D','', str(shield.get('value',0))))

          out = subprocess.check_output([
            'pypinfo', 'feloopy', 'country', '--json', '--limit', '200'
          ])
          stats['by_country'] = json.loads(out)

          html = requests.get('https://www.youtube.com/@feloopy/about').text
          soup = BeautifulSoup(html, 'html.parser')

          sub = soup.select_one('yt-formatted-string#subscriber-count')
          stats['youtube_subs'] = sub.text.strip() if sub else 'n/a'

          view = soup.select_one('span.about-stat:nth-of-type(2) b')
          stats['youtube_views'] = view.text.strip() if view else 'n/a'

          stats['fetched_at'] = datetime.datetime.utcnow().isoformat()+'Z'

          with open('stats.json','w') as f: json.dump(stats, f, indent=2)
          EOF

      - name: Commit & push
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add stats.json
          git diff --staged --quiet || git commit -m "Update stats.json"
          git push
