name: Fetch Feloopy Stats

# Scheduled (daily at 00:00 UTC) and manual trigger
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo so we can commit stats.json :contentReference[oaicite:3]{index=3}
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Install Python for pypistats :contentReference[oaicite:4]{index=4}
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3️⃣ Install pypistats & requests
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pypistats requests

      # 4️⃣ Fetch stats via pypistats (no CORS issues, server-side) & GitHub API  
      - name: Fetch PyPI downloads & GitHub stars
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python - << 'EOF'
          import os
          import json
          from pypistats import recent        # attribute-based API :contentReference[oaicite:5]{index=5}
          import requests

          # Correct attribute access (not dict indexing) :contentReference[oaicite:6]{index=6}
          week = recent("feloopy", period="week").data.last_week
          month = recent("feloopy", period="month").data.last_month

          # GitHub stars (authenticated to avoid rate-limit) :contentReference[oaicite:7]{index=7}
          resp = requests.get(
              "https://api.github.com/repos/feloopy/feloopy",
              headers={"Authorization": f"token {os.environ['GITHUB_TOKEN']}"}
          )
          stars = resp.json().get("stargazers_count", 0)

          # Write same-origin JSON for GitHub Pages (CORS-friendly) :contentReference[oaicite:8]{index=8}
          stats = {"week": week, "month": month, "stars": stars}
          with open("stats.json", "w") as f:
              json.dump(stats, f)
          EOF

      # 5️⃣ Commit & push stats.json back to main :contentReference[oaicite:9]{index=9}
      - name: Commit stats.json
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add stats.json
          git diff --staged --quiet || git commit -m "Update stats.json"
          git push
